FROM node:20-alpine

WORKDIR /app

# Install dependencies
COPY package.json package-lock.json ./
RUN npm ci --include=optional

# Copy the rest of the app
COPY . .

# Expose the app port
EXPOSE 3000

# Start the application in Next.js dev mode
CMD ["npm", "run", "dev"]
